use super::types::{HciEvtDef, ParamType};

pub fn lookup(code: u8) -> Option<&'static HciEvtDef> {
    TABLE.iter().find(|e| e.code == code)
}

static TABLE: &[HciEvtDef] = &[
    HciEvtDef {
        code: 0x01,
        name: "LE_Connection_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Role", ParamType::U8),
            ("Peer_Address_Type", ParamType::U8),
            ("Peer_Address", ParamType::BdAddr),
            ("Conn_Interval", ParamType::U16),
            ("Conn_Latency", ParamType::U16),
            ("Supervision_Timeout", ParamType::U16),
            ("Central_Clock_Accuracy", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x02,
        name: "LE_Advertising_Report",
        params: &[("Num_Reports", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x03,
        name: "LE_Connection_Update_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Conn_Interval", ParamType::U16),
            ("Conn_Latency", ParamType::U16),
            ("Supervision_Timeout", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x04,
        name: "LE_Read_Remote_Features_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("LE_Features", ParamType::Bytes(8)),
        ],
    },
    HciEvtDef {
        code: 0x05,
        name: "LE_Long_Term_Key_Request",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("Random_Number", ParamType::Bytes(8)),
            ("Encrypted_Diversifier", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x06,
        name: "LE_Remote_Connection_Parameter_Request",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("Interval_Min", ParamType::U16),
            ("Interval_Max", ParamType::U16),
            ("Latency", ParamType::U16),
            ("Timeout", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x07,
        name: "LE_Data_Length_Change",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("MaxTxOctets", ParamType::U16),
            ("MaxTxTime", ParamType::U16),
            ("MaxRxOctets", ParamType::U16),
            ("MaxRxTime", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x08,
        name: "LE_Read_Local_P256_Public_Key_Complete",
        params: &[("Status", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x09,
        name: "LE_Generate_DHKey_Complete",
        params: &[("Status", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x0A,
        name: "LE_Enhanced_Connection_Complete_V1",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Role", ParamType::U8),
            ("Peer_Address_Type", ParamType::U8),
            ("Peer_Address", ParamType::BdAddr),
            ("Local_Resolvable_Private_Address", ParamType::BdAddr),
            ("Peer_Resolvable_Private_Address", ParamType::BdAddr),
            ("Conn_Interval", ParamType::U16),
            ("Conn_Latency", ParamType::U16),
            ("Supervision_Timeout", ParamType::U16),
            ("Central_Clock_Accuracy", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x0B,
        name: "LE_Directed_Advertising_Report",
        params: &[("Num_Reports", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x0C,
        name: "LE_PHY_Update_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("TX_PHY", ParamType::U8),
            ("RX_PHY", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x0D,
        name: "LE_Extended_Advertising_Report",
        params: &[("Num_Reports", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x0E,
        name: "LE_Periodic_Advertising_Sync_Established",
        params: &[
            ("Status", ParamType::U8),
            ("Sync_Handle", ParamType::U16),
            ("Advertising_SID", ParamType::U8),
            ("Advertiser_Address_Type", ParamType::U8),
            ("Advertiser_Address", ParamType::BdAddr),
            ("Advertiser_PHY", ParamType::U8),
            ("Periodic_Advertising_Interval", ParamType::U16),
            ("Advertiser_Clock_Accuracy", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x0F,
        name: "LE_Periodic_Advertising_Report",
        params: &[
            ("Sync_Handle", ParamType::U16),
            ("TX_Power", ParamType::U8),
            ("RSSI", ParamType::U8),
            ("CTE_Type", ParamType::U8),
            ("Data_Status", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x10,
        name: "LE_Periodic_Advertising_Sync_Lost",
        params: &[("Sync_Handle", ParamType::U16)],
    },
    HciEvtDef {
        code: 0x11,
        name: "LE_Scan_Timeout",
        params: &[],
    },
    HciEvtDef {
        code: 0x12,
        name: "LE_Advertising_Set_Terminated",
        params: &[
            ("Status", ParamType::U8),
            ("Advertising_Handle", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Num_Completed_Extended_Advertising_Events", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x13,
        name: "LE_Scan_Request_Received",
        params: &[
            ("Advertising_Handle", ParamType::U8),
            ("Scanner_Address_Type", ParamType::U8),
            ("Scanner_Address", ParamType::BdAddr),
        ],
    },
    HciEvtDef {
        code: 0x14,
        name: "LE_Channel_Selection_Algorithm",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("Channel_Selection_Algorithm", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x15,
        name: "LE_Connectionless_IQ_Report",
        params: &[
            ("Sync_Handle", ParamType::U16),
            ("Channel_Index", ParamType::U8),
            ("RSSI", ParamType::U16),
            ("RSSI_Antenna_ID", ParamType::U8),
            ("CTE_Type", ParamType::U8),
            ("Slot_Durations", ParamType::U8),
            ("Packet_Status", ParamType::U8),
            ("Connection_Event_Counter", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x16,
        name: "LE_Connection_IQ_Report",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("RX_PHY", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x17,
        name: "LE_CTE_Request_Failed",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x18,
        name: "LE_Periodic_Adv_Sync_Transfer_Received",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Service_Data", ParamType::U16),
            ("Sync_Handle", ParamType::U16),
            ("Advertising_SID", ParamType::U8),
            ("Advertiser_Address_Type", ParamType::U8),
            ("Advertiser_Address", ParamType::BdAddr),
            ("Advertiser_PHY", ParamType::U8),
            ("Periodic_Advertising_Interval", ParamType::U16),
            ("Advertiser_Clock_Accuracy", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x19,
        name: "LE_CIS_Established",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("CIG_Sync_Delay", ParamType::U24),
            ("CIS_Sync_Delay", ParamType::U24),
            ("Transport_Latency_C_To_P", ParamType::U24),
            ("Transport_Latency_P_To_C", ParamType::U24),
            ("PHY_C_To_P", ParamType::U8),
            ("PHY_P_To_C", ParamType::U8),
            ("NSE", ParamType::U8),
            ("BN_C_To_P", ParamType::U8),
            ("BN_P_To_C", ParamType::U8),
            ("FT_C_To_P", ParamType::U8),
            ("FT_P_To_C", ParamType::U8),
            ("Max_PDU_C_To_P", ParamType::U16),
            ("Max_PDU_P_To_C", ParamType::U16),
            ("ISO_Interval", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x1A,
        name: "LE_CIS_Request",
        params: &[
            ("ACL_Connection_Handle", ParamType::U16),
            ("CIS_Connection_Handle", ParamType::U16),
            ("CIG_ID", ParamType::U8),
            ("CIS_ID", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x1B,
        name: "LE_Create_BIG_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("BIG_Handle", ParamType::U8),
            ("BIG_Sync_Delay", ParamType::U24),
            ("Transport_Latency_BIG", ParamType::U24),
            ("PHY", ParamType::U8),
            ("NSE", ParamType::U8),
            ("BN", ParamType::U8),
            ("PTO", ParamType::U8),
            ("IRC", ParamType::U8),
            ("Max_PDU", ParamType::U16),
            ("ISO_Interval", ParamType::U16),
            ("Num_BIS", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x1C,
        name: "LE_Terminate_BIG_Complete",
        params: &[("BIG_Handle", ParamType::U8), ("Reason", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x1D,
        name: "LE_BIG_Sync_Established",
        params: &[
            ("Status", ParamType::U8),
            ("BIG_Handle", ParamType::U8),
            ("Transport_Latency_BIG", ParamType::U24),
            ("NSE", ParamType::U8),
            ("BN", ParamType::U8),
            ("PTO", ParamType::U8),
            ("IRC", ParamType::U8),
            ("Max_PDU", ParamType::U16),
            ("ISO_Interval", ParamType::U16),
            ("Num_BIS", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x1E,
        name: "LE_BIG_Sync_Lost",
        params: &[("BIG_Handle", ParamType::U8), ("Reason", ParamType::U8)],
    },
    HciEvtDef {
        code: 0x1F,
        name: "LE_Request_Peer_SCA_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Peer_Clock_Accuracy", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x20,
        name: "LE_Path_Loss_Threshold",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("Current_Path_Loss", ParamType::U8),
            ("Zone_Entered", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x21,
        name: "LE_Transmit_Power_Reporting",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Reason", ParamType::U8),
            ("PHY", ParamType::U8),
            ("TX_Power", ParamType::U8),
            ("TX_Power_Flag", ParamType::U8),
            ("Delta", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x22,
        name: "LE_BIGInfo_Advertising_Report",
        params: &[
            ("Sync_Handle", ParamType::U16),
            ("Num_BIS", ParamType::U8),
            ("NSE", ParamType::U8),
            ("ISO_Interval", ParamType::U16),
            ("BN", ParamType::U8),
            ("PTO", ParamType::U8),
            ("IRC", ParamType::U8),
            ("Max_PDU", ParamType::U16),
            ("SDU_Interval", ParamType::U24),
            ("Max_SDU", ParamType::U16),
            ("PHY", ParamType::U8),
            ("Framing", ParamType::U8),
            ("Encryption", ParamType::U8),
        ],
    },
    HciEvtDef {
        code: 0x23,
        name: "LE_Subrate_Change",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Subrate_Factor", ParamType::U16),
            ("Peripheral_Latency", ParamType::U16),
            ("Continuation_Number", ParamType::U16),
            ("Supervision_Timeout", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x2B,
        name: "LE_Read_All_Remote_Features_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Max_Page_Number", ParamType::U8),
            ("Valid_Page_Bits", ParamType::U8),
            ("LE_Features", ParamType::Bytes(0)),
        ],
    },
    HciEvtDef {
        code: 0x2C,
        name: "LE_CS_Read_Remote_Supported_Capabilities_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Parameters", ParamType::Bytes(0)),
        ],
    },
    HciEvtDef {
        code: 0x2D,
        name: "LE_CS_Read_Remote_FAE_Table_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Remote_FAE_Table", ParamType::Bytes(72)),
        ],
    },
    HciEvtDef {
        code: 0x2E,
        name: "LE_CS_Security_Enable_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
        ],
    },
    HciEvtDef {
        code: 0x2F,
        name: "LE_CS_Config_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Config_ID", ParamType::U8),
            ("Action", ParamType::U8),
            ("Parameters", ParamType::Bytes(0)),
        ],
    },
    HciEvtDef {
        code: 0x30,
        name: "LE_CS_Procedure_Enable_Complete",
        params: &[
            ("Status", ParamType::U8),
            ("Connection_Handle", ParamType::U16),
            ("Config_ID", ParamType::U8),
            ("State", ParamType::U8),
            ("Parameters", ParamType::Bytes(0)),
        ],
    },
    HciEvtDef {
        code: 0x31,
        name: "LE_CS_Subevent_Result",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("Config_ID", ParamType::U8),
            ("Start_ACL_Connection_Event_Counter", ParamType::U16),
            ("Procedure_Counter", ParamType::U16),
            ("Frequency_Compensation", ParamType::U16),
            ("Reference_Power_Level", ParamType::U8),
            ("Procedure_Done_Status", ParamType::U8),
            ("Subevent_Done_Status", ParamType::U8),
            ("Abort_Reason", ParamType::U8),
            ("Num_Antenna_Paths", ParamType::U8),
            ("Num_Steps_Reported", ParamType::U8),
            ("Step_Data", ParamType::Bytes(0)),
        ],
    },
    HciEvtDef {
        code: 0x32,
        name: "LE_CS_Subevent_Result_Continue",
        params: &[
            ("Connection_Handle", ParamType::U16),
            ("Config_ID", ParamType::U8),
            ("Procedure_Done_Status", ParamType::U8),
            ("Subevent_Done_Status", ParamType::U8),
            ("Abort_Reason", ParamType::U8),
            ("Num_Antenna_Paths", ParamType::U8),
            ("Num_Steps_Reported", ParamType::U8),
            ("Step_Data", ParamType::Bytes(0)),
        ],
    },
    HciEvtDef {
        code: 0x33,
        name: "LE_CS_Test_End_Complete",
        params: &[("Status", ParamType::U8)],
    },
];
